files:
  - source: /src/locales/en/ui.yml
    translation: /src/locales/%locale%/%original_file_name%
  - source: /src/external/seo/en_US/seo.yml
    translation: /src/external/seo/%locale%/%original_file_name%